name: Publish to CANFAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the SSIM Docker image
      run: docker build --target deploy --build-arg VERSION=python -t ssim:python -f Dockerfile .
      run: docker login --username ${{ secrets.IMAGES_CANFAR_LOGIN}} --password ${{ IMAGES_CANFAR_TOKEN}}
      run: docker push ssim:python
